import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import type { Loader, LoaderContext } from 'astro/loaders';
// Zod comes from `astro/zod`, not the `z` re-export on `astro:content` (which
// Astro 7 deprecates) and not a direct `zod` dependency — this is the exact
// build Astro validates frontmatter with, so the schema and the validator
// cannot drift apart on a version bump.
import { z } from 'astro/zod';

const ACCESSION = /^\d{4}\.\d{2}$/;
const RECORDS_BASE = './src/content/records';

/**
 * A record is a container, not a page. It lives in a directory named
 * `{acc}-{slug}` and holds an `index.mdx`.
 *
 * Ids are generated by hand rather than by Astro's default, which slugifies:
 * it would turn `2026.04-rochester-map` into `2026-04-rochester-map` and take
 * the dot out of the accession number, which is the one character that makes
 * `2026.04` an identifier rather than a date. Every derivation below reads the
 * id, so the id has to stay lossless.
 *
 *   records   2026.04-rochester-map
 */
const recordId = (entry: string) => entry.replace(/\/index\.mdx$/i, '');

/** The leading `YYYY.NN` of a record directory name, or null if absent. */
const accFromDirectory = (directory: string): string | null =>
	ACCESSION.test(directory.slice(0, 7)) ? directory.slice(0, 7) : null;

/**
 * Records: accession numbers are unique across the register, and the directory
 * name states the same accession as the frontmatter.
 *
 * A Zod schema can validate the shape of one number but cannot see the others,
 * and cannot see the path at all — so both guards run after the load, over the
 * whole collection.
 *
 * These throw rather than warn. A reused accession is a silent lie about the
 * register's history; a directory disagreeing with its own frontmatter means
 * there are two answers to "which record is this" and no way to tell which is
 * authoritative. Neither may be shippable by not reading the build log.
 */
function withRecordGuards(loader: Loader): Loader {
	return {
		...loader,
		name: `${loader.name}+record-guards`,
		load: async (context: LoaderContext) => {
			await loader.load(context);

			const claimed = new Map<string, string>();
			const duplicates: string[] = [];
			const mismatched: string[] = [];

			for (const entry of context.store.values()) {
				const acc = (entry.data as { acc?: unknown }).acc;
				if (typeof acc !== 'string') continue;

				const directoryAcc = accFromDirectory(entry.id);
				if (directoryAcc === null) {
					mismatched.push(
						`  "${entry.id}" — directory name must begin with an accession number, e.g. "${acc}-some-slug"`,
					);
				} else if (directoryAcc !== acc) {
					mismatched.push(
						`  "${entry.id}" — directory says ${directoryAcc}, frontmatter says ${acc}`,
					);
				}

				const prior = claimed.get(acc);
				if (prior === undefined) {
					claimed.set(acc, entry.id);
				} else {
					duplicates.push(`  ${acc} — claimed by both "${prior}" and "${entry.id}"`);
				}
			}

			if (mismatched.length > 0) {
				throw new Error(
					`Record directory name does not match its accession number:\n${mismatched.join('\n')}\n\n` +
						`A record directory is named {acc}-{slug}. The directory and the frontmatter ` +
						`are one source of truth, checked rather than trusted — rename the directory ` +
						`or correct the frontmatter so they agree.`,
				);
			}

			if (duplicates.length > 0) {
				throw new Error(
					`Duplicate accession number${duplicates.length > 1 ? 's' : ''} in the records ` +
						`collection:\n${duplicates.join('\n')}\n\n` +
						`Accession numbers are assigned in order of entry and are never reused. ` +
						`Give the newer record the next unclaimed number for its year.`,
				);
			}
		},
	};
}

const records = defineCollection({
	loader: withRecordGuards(
		glob({
			base: RECORDS_BASE,
			pattern: '*/index.mdx',
			generateId: ({ entry }) => recordId(entry),
		}),
	),
	schema: z
		.strictObject({
			// YYYY.NN — the fourth work entered in 2026 is 2026.04. Carries output
			// rate and history without any claim being made about the work.
			acc: z.string().regex(ACCESSION, 'accession numbers are YYYY.NN, e.g. 2026.04'),

			title: z.string().min(1),
			summary: z.string().min(1),

			client: z.string().min(1).optional(),
			role: z.string().min(1),

			// MEDIUM, never "stack" or "tech". The field name is the theme.
			medium: z.array(z.string().min(1)).nonempty(),

			acquired: z.date(),
			completed: z.date().optional(),

			status: z.enum(['active', 'shipped', 'archived']),

			// Extent is measured: 118 commits · 7 weeks. Every part is optional
			// because a record should state only what was actually counted — a
			// guessed number is worse than an absent one. `loc` was here through
			// Phase 3.1; dropped in 3.2 because it invites comparing 4,176 lines
			// in two days against 1,726 over eight weeks, and the bigger number
			// reads as generated volume rather than more work.
			extent: z
				.strictObject({
					commits: z.number().int().positive().optional(),
					duration: z.string().min(1).optional(),
				})
				.default({}),

			// Required, and deliberately so. Every record states its actual state:
			// "Stable. Deps current as of Jun 2026." / "Archived — don't run it."
			// This is the most differentiating field in the system and the one most
			// likely to be softened into uselessness.
			condition: z.string().min(1),

			locality: z.string().min(1).optional(),

			// The register's change log: condition moving from active to shipped, a
			// revision, an accrual filed. Phase 2 builds a recent-changes panel from
			// the union of accessions, filings, and these. No consumer yet.
			history: z
				.array(
					z.strictObject({
						date: z.date(),
						note: z.string().min(1),
					}),
				)
				.optional(),

			links: z
				.strictObject({
					live: z.url().optional(),
					source: z.url().optional(),
					// Usually external (a Medium post, a client write-up elsewhere),
					// but a root-relative path is also accepted for one filed
					// in-site.
					writeup: z.union([z.url(), z.string().startsWith('/')]).optional(),
				})
				.default({}),

			featured: z.boolean().default(false),
			order: z.number().int(),
		})
		.refine((r) => r.status !== 'shipped' || r.completed !== undefined, {
			message: 'a record with status "shipped" needs a `completed` date',
			path: ['completed'],
		})
		.refine((r) => r.completed === undefined || r.completed >= r.acquired, {
			message: '`completed` cannot precede `acquired`',
			path: ['completed'],
		}),
	// No refine tying the accession year to `acquired`. The accession year is
	// when the work entered the register; `acquired` is when the work was made.
	// Those diverge routinely — a 2024 project catalogued today is 2026.NN, and
	// that is correct rather than incoherent.
});

/**
 * The person, not a work. One entry — the masthead and the biographical
 * note both read from it, so the two surfaces can't state the name or role
 * differently by accident.
 *
 * `chronology` dates are optional and deliberately so: a chronology entry
 * with no `date` is not a bug, it's an entry nobody has filled in a real
 * date for yet. Nothing here is allowed to guess a graduation year or an
 * employment date on Langston's behalf.
 */
const profile = defineCollection({
	loader: glob({ base: './src/content', pattern: 'profile.yaml', generateId: () => 'profile' }),
	schema: z.strictObject({
		name: z.string().min(1),
		role: z.string().min(1),
		location: z.string().min(1),
		institution: z.string().min(1),

		// Not `.email()`/`.url()`-validated even though they hold an email and
		// a URL respectively: a field carrying the literal [[UNWRITTEN]]
		// sentinel has to pass schema validation too (isUnwritten() is what
		// keeps it off the page, not the schema), so these stay plain strings
		// the same way `availability` already does.
		degree: z.string().min(1),
		graduation: z.string().min(1),
		gpa: z.string().min(1),
		email: z.string().min(1),
		services: z.string().min(1),

		// Real and always present — the account this whole site's GitHub panel
		// already reads from — so this is the one contact-adjacent field with
		// no unwritten state to handle.
		githubProfile: z.url(),
		linkedinProfile: z.url(),

		// The live field — never a decoration. Prose, not a status enum,
		// because "current availability" doesn't collapse cleanly into a
		// fixed set of states without losing the nuance a client needs.
		availability: z.string().min(1),

		chronology: z
			.array(
				z.strictObject({
					date: z.date().optional(),
					kind: z.enum(['education', 'freelance', 'employment']),
					// title/org replace what used to be one combined `note` string
					// ("Title, Org — description") — split so the collapsed row can
					// show position and organization as their own lines instead of
					// parsing them back out of a sentence. `summary` is the short
					// description that sentence used to end in; it now surfaces only
					// on expand, as the lead line above `detail`.
					title: z.string().min(1),
					org: z.string().min(1),
					summary: z.string().min(1).optional(),
					// `detail` is the full description, shown only on expand — a
					// <details> disclosure, not a second source of truth for the same
					// fact. An array, not a paragraph: these came from LinkedIn as
					// bullet points, and a role with five responsibilities reads as
					// five responsibilities, not one 90-word block a reader has to
					// parse apart themselves.
					detail: z.array(z.string().min(1)).min(1).optional(),
				}),
			)
			.default([]),
	}),
});

export const collections = { records, profile };
