import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import type { Loader, LoaderContext } from 'astro/loaders';
// Zod comes from `astro/zod`, not the `z` re-export on `astro:content` (which
// Astro 7 deprecates) and not a direct `zod` dependency — this is the exact
// build Astro validates frontmatter with, so the schema and the validator
// cannot drift apart on a version bump.
import { z } from 'astro/zod';

const ACCESSION = /^\d{4}\.\d{2}$/;
const RECORDS_BASE = './src/content/records';

/**
 * A record is a container, not a page. It lives in a directory named
 * `{acc}-{slug}` and holds an `index.mdx` plus any number of accruals filed
 * under `articles/`.
 *
 * Ids are generated by hand rather than by Astro's default, which slugifies:
 * it would turn `2026.04-rochester-map` into `2026-04-rochester-map` and take
 * the dot out of the accession number, which is the one character that makes
 * `2026.04` an identifier rather than a date. Every derivation below reads the
 * id, so the id has to stay lossless.
 *
 *   records   2026.04-rochester-map
 *   articles  2026.04-rochester-map/01-overpass-extraction
 */
const recordId = (entry: string) => entry.replace(/\/index\.mdx$/i, '');

const articleId = (entry: string) => {
	const [directory = '', file = ''] = [
		entry.slice(0, entry.indexOf('/')),
		entry.slice(entry.lastIndexOf('/') + 1).replace(/\.mdx$/i, ''),
	];
	return `${directory}/${file}`;
};

/** The leading `YYYY.NN` of a record directory name, or null if absent. */
const accFromDirectory = (directory: string): string | null =>
	ACCESSION.test(directory.slice(0, 7)) ? directory.slice(0, 7) : null;

/**
 * Records: accession numbers are unique across the register, and the directory
 * name states the same accession as the frontmatter.
 *
 * A Zod schema can validate the shape of one number but cannot see the others,
 * and cannot see the path at all — so both guards run after the load, over the
 * whole collection.
 *
 * These throw rather than warn. A reused accession is a silent lie about the
 * register's history; a directory disagreeing with its own frontmatter means
 * there are two answers to "which record is this" and no way to tell which is
 * authoritative. Neither may be shippable by not reading the build log.
 */
function withRecordGuards(loader: Loader): Loader {
	return {
		...loader,
		name: `${loader.name}+record-guards`,
		load: async (context: LoaderContext) => {
			await loader.load(context);

			const claimed = new Map<string, string>();
			const duplicates: string[] = [];
			const mismatched: string[] = [];

			for (const entry of context.store.values()) {
				const acc = (entry.data as { acc?: unknown }).acc;
				if (typeof acc !== 'string') continue;

				const directoryAcc = accFromDirectory(entry.id);
				if (directoryAcc === null) {
					mismatched.push(
						`  "${entry.id}" — directory name must begin with an accession number, e.g. "${acc}-some-slug"`,
					);
				} else if (directoryAcc !== acc) {
					mismatched.push(
						`  "${entry.id}" — directory says ${directoryAcc}, frontmatter says ${acc}`,
					);
				}

				const prior = claimed.get(acc);
				if (prior === undefined) {
					claimed.set(acc, entry.id);
				} else {
					duplicates.push(`  ${acc} — claimed by both "${prior}" and "${entry.id}"`);
				}
			}

			if (mismatched.length > 0) {
				throw new Error(
					`Record directory name does not match its accession number:\n${mismatched.join('\n')}\n\n` +
						`A record directory is named {acc}-{slug}. The directory and the frontmatter ` +
						`are one source of truth, checked rather than trusted — rename the directory ` +
						`or correct the frontmatter so they agree.`,
				);
			}

			if (duplicates.length > 0) {
				throw new Error(
					`Duplicate accession number${duplicates.length > 1 ? 's' : ''} in the records ` +
						`collection:\n${duplicates.join('\n')}\n\n` +
						`Accession numbers are assigned in order of entry and are never reused. ` +
						`Give the newer record the next unclaimed number for its year.`,
				);
			}
		},
	};
}

/**
 * Articles: the parent record's accession is injected as `record` before
 * validation, and note numbers are unique within each parent.
 *
 * The injection wraps `parseData` rather than rewriting the store afterwards.
 * That ordering matters: injecting first means `record` is a required,
 * regex-checked field of the schema like any other, so it appears in the
 * generated types and Phase 2 can read `article.data.record` directly instead
 * of re-parsing an id in a template. Rewriting the store afterwards would
 * produce a value the type system knows nothing about.
 *
 * Anything an author writes in a `record:` frontmatter key is overwritten. The
 * directory is the only source of that fact.
 */
function withArticleGuards(loader: Loader): Loader {
	return {
		...loader,
		name: `${loader.name}+article-guards`,
		load: async (context: LoaderContext) => {
			const withInjectedRecord: LoaderContext = {
				...context,
				parseData: (props) =>
					context.parseData({
						...props,
						data: {
							...props.data,
							record: accFromDirectory(props.id.slice(0, props.id.indexOf('/'))) ?? '',
						},
					}),
			};

			await loader.load(withInjectedRecord);

			// note is the accrual's identifier within its record — "2026.04, note 3".
			// Scoped per record, so two different records may both have a note 1.
			const claimed = new Map<string, Map<number, string>>();
			const duplicates: string[] = [];

			for (const entry of context.store.values()) {
				const { record, note } = entry.data as { record?: unknown; note?: unknown };
				if (typeof record !== 'string' || typeof note !== 'number') continue;

				const withinRecord = claimed.get(record) ?? new Map<number, string>();
				const prior = withinRecord.get(note);
				if (prior === undefined) {
					withinRecord.set(note, entry.id);
					claimed.set(record, withinRecord);
				} else {
					duplicates.push(
						`  ${record}, note ${note} — claimed by both "${prior}" and "${entry.id}"`,
					);
				}
			}

			if (duplicates.length > 0) {
				throw new Error(
					`Duplicate note number${duplicates.length > 1 ? 's' : ''} within a record:\n` +
						`${duplicates.join('\n')}\n\n` +
						`Note numbers identify an accrual within its record and are assigned in ` +
						`order of filing. They are never reused. Filename prefixes are sort order ` +
						`and can be renamed freely; the note number cannot.`,
				);
			}
		},
	};
}

const records = defineCollection({
	loader: withRecordGuards(
		glob({
			base: RECORDS_BASE,
			pattern: '*/index.mdx',
			generateId: ({ entry }) => recordId(entry),
		}),
	),
	schema: z
		.strictObject({
			// YYYY.NN — the fourth work entered in 2026 is 2026.04. Carries output
			// rate and history without any claim being made about the work.
			acc: z.string().regex(ACCESSION, 'accession numbers are YYYY.NN, e.g. 2026.04'),

			title: z.string().min(1),
			summary: z.string().min(1),

			client: z.string().min(1).optional(),
			role: z.string().min(1),

			// MEDIUM, never "stack" or "tech". The field name is the theme.
			medium: z.array(z.string().min(1)).nonempty(),

			acquired: z.date(),
			completed: z.date().optional(),

			status: z.enum(['active', 'shipped', 'archived']),

			// Extent is measured: 4,180 LOC · 118 commits · 7 weeks. Every part is
			// optional because a record should state only what was actually counted
			// — a guessed number is worse than an absent one.
			extent: z
				.strictObject({
					loc: z.number().int().positive().optional(),
					commits: z.number().int().positive().optional(),
					duration: z.string().min(1).optional(),
				})
				.default({}),

			// Required, and deliberately so. Every record states its actual state:
			// "Stable. Deps current as of Jun 2026." / "Archived — don't run it."
			// This is the most differentiating field in the system and the one most
			// likely to be softened into uselessness.
			condition: z.string().min(1),

			locality: z.string().min(1).optional(),

			// The register's change log: condition moving from active to shipped, a
			// revision, an accrual filed. Phase 2 builds a recent-changes panel from
			// the union of accessions, filings, and these. No consumer yet.
			history: z
				.array(
					z.strictObject({
						date: z.date(),
						note: z.string().min(1),
					}),
				)
				.optional(),

			links: z
				.strictObject({
					live: z.url().optional(),
					source: z.url().optional(),
					// A writeup is usually an accrual on this site, so this one field
					// also accepts a root-relative path.
					writeup: z.union([z.url(), z.string().startsWith('/')]).optional(),
				})
				.default({}),

			featured: z.boolean().default(false),
			order: z.number().int(),
		})
		.refine((r) => r.status !== 'shipped' || r.completed !== undefined, {
			message: 'a record with status "shipped" needs a `completed` date',
			path: ['completed'],
		})
		.refine((r) => r.completed === undefined || r.completed >= r.acquired, {
			message: '`completed` cannot precede `acquired`',
			path: ['completed'],
		}),
	// No refine tying the accession year to `acquired`. The accession year is
	// when the work entered the register; `acquired` is when the work was made.
	// Those diverge routinely — a 2024 project catalogued today is 2026.NN, and
	// that is correct rather than incoherent.
});

const articles = defineCollection({
	loader: withArticleGuards(
		glob({
			base: RECORDS_BASE,
			pattern: '*/articles/*.mdx',
			generateId: ({ entry }) => articleId(entry),
		}),
	),
	schema: z.strictObject({
		// Injected from the parent directory before validation. Never authored.
		record: z.string().regex(ACCESSION),

		// The accrual's identifier within its record: "2026.04, note 3". Assigned
		// in order of filing, never reused. Deliberately NOT derived from the
		// filename — the `01-` prefix is sort order for a directory listing and
		// can be renamed at will; an identifier cannot.
		note: z.number().int().positive(),

		title: z.string().min(1),
		summary: z.string().min(1),

		filed: z.date(),

		// Required for the same reason `condition` is required on a record: the
		// state of the thing is part of the thing.
		condition: z.enum(['draft', 'revised', 'final']),

		// What occasioned the piece.
		provenance: z.string().min(1).optional(),

		extent: z
			.strictObject({
				words: z.number().int().positive().optional(),
			})
			.optional(),

		// Defaults to true so a half-written accrual cannot ship by omission.
		// Publishing is an explicit act.
		draft: z.boolean().default(true),
	}),
});

export const collections = { records, articles };
